services:
  - type: web
    name: telegram-fsub-bot
    env: python
    build:
      dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        fromService:
          name: telegram-fsub-bot
          type: secret
      - key: MONGO_URI
        fromService:
          name: telegram-fsub-bot
          type: secret
    healthCheckPath: /
    port: 8000
    plan: free
